server:
  port: 8443
  ssl:
    key-store: E:\\Files\\shellTest\\mykeys.jks
    key-store-password: letmein
    key-password: letmein


amazon:
  associatedId: habuma

logging:
  path: E:\\Files\\shellTest\\
  config:
    classpath: logback.xml #配置文件
spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reading?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #使用redis作为cache
  cache:
    type: redis
  #Spring Session设置
  session:
    store-type: redis
    timeout: 100000
    redis:
      flush-mode: immediate
      namespace: spring:session
  #redis设置
  redis:
    host: localhost
    port: 6379
    #密码默认为空
    password:
    timeout: 10000
    #默认有16个分片，使用第0个分片，存储在一定时间后自动删除
    database: 0
    #lettuce配置
    lettuce:
      pool:
        max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
    # 连接池中的最大空闲连接 默认 8
        max-idle: 8
    # 连接池中的最小空闲连接 默认 0
        min-idle: 0

#mybatis:
#  type-aliases-package: com.reborn.readinglist.entity



---

spring:
  profiles:
    active: development

logging:
  level:
    root: DEBUG
  file: readingList-dev.log

---
#使用---作为分隔符,第一部分是通用设置，因为没有指定profiles的属性
#Profile属性设置
spring:
  profiles:
    active: production

logging:
  level:
    root: WARN #根日志级别设置为WARN
    org.springframework.security: DEBUG #Security日志级别设置为DEBUG
  file: readingList-pro.log

#配置数据库
#spring:
#  datasource:
#    jndi-name:

